before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install coffeelint
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec spork &

script:
  - bundle exec rake test
