--- !ditz.rubyforge.org,2008-03-06/project 
name: gorilla
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: gorilla
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: Iteration 1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2013-03-13 08:53:49.648189 Z
    - Zachary Michael Bush <zach@zmbush.com>
    - created
    - Iteration one. Due Friday March 15
